name: Collect cock ratings

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  four-chan:
    name: Collect cock ratings from 4chan threads
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Initialize environment
        run: npm install --production

      - name: Run collection script
        run: npm start
      

